create table _user (id integer not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role enum ('USER','ADMIN'), primary key (id)) engine=InnoDB;
create table account (birth datetime(6), id bigint not null, address varchar(255), email varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table account_seq (next_val bigint) engine=InnoDB;
insert into account_seq values ( 1 );
create table movie (runtime integer not null, genre varchar(255) not null, title varchar(255) not null, primary key (title)) engine=InnoDB;
create table room (col_count integer not null, row_count integer not null, room_name varchar(255) not null, primary key (room_name)) engine=InnoDB;
create table screening (screening_id integer not null auto_increment, start_time datetime(6) not null, movie_title_id varchar(255) not null, room_room_name_id varchar(255) not null, primary key (screening_id)) engine=InnoDB;
alter table _user add constraint UK_k11y3pdtsrjgy8w9b6q4bjwrx unique (email);
alter table screening add constraint FKg0h7o7un2cypdgqwpfmqohjiu foreign key (movie_title_id) references movie (title);
alter table screening add constraint FKtrw3ri1tre3m76deqsp2d6xqx foreign key (room_room_name_id) references room (room_name);
create table _user (id integer not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role enum ('USER','ADMIN'), primary key (id)) engine=InnoDB;
create table account (birth datetime(6), id bigint not null, address varchar(255), email varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table account_seq (next_val bigint) engine=InnoDB;
insert into account_seq values ( 1 );
create table movie (runtime integer not null, genre varchar(255) not null, title varchar(255) not null, primary key (title)) engine=InnoDB;
create table room (col_count integer not null, row_count integer not null, room_name varchar(255) not null, primary key (room_name)) engine=InnoDB;
create table screening (screening_id integer not null auto_increment, start_time datetime(6) not null, movie_title_id varchar(255) not null, room_room_name_id varchar(255) not null, primary key (screening_id)) engine=InnoDB;
alter table _user add constraint UK_k11y3pdtsrjgy8w9b6q4bjwrx unique (email);
alter table screening add constraint FKg0h7o7un2cypdgqwpfmqohjiu foreign key (movie_title_id) references movie (title);
alter table screening add constraint FKtrw3ri1tre3m76deqsp2d6xqx foreign key (room_room_name_id) references room (room_name);
create table _user (id integer not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role enum ('USER','ADMIN'), primary key (id)) engine=InnoDB;
create table account (birth datetime(6), id bigint not null, address varchar(255), email varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table account_seq (next_val bigint) engine=InnoDB;
insert into account_seq values ( 1 );
create table movie (runtime integer not null, genre varchar(255) not null, title varchar(255) not null, primary key (title)) engine=InnoDB;
create table room (col_count integer not null, row_count integer not null, room_name varchar(255) not null, primary key (room_name)) engine=InnoDB;
create table screening (screening_id integer not null auto_increment, start_time datetime(6) not null, movie_title_id varchar(255) not null, room_room_name_id varchar(255) not null, primary key (screening_id)) engine=InnoDB;
alter table _user add constraint UK_k11y3pdtsrjgy8w9b6q4bjwrx unique (email);
alter table screening add constraint FKg0h7o7un2cypdgqwpfmqohjiu foreign key (movie_title_id) references movie (title);
alter table screening add constraint FKtrw3ri1tre3m76deqsp2d6xqx foreign key (room_room_name_id) references room (room_name);
create table _user (id integer not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role enum ('USER','ADMIN'), primary key (id)) engine=InnoDB;
create table account (birth datetime(6), id bigint not null, address varchar(255), email varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table account_seq (next_val bigint) engine=InnoDB;
insert into account_seq values ( 1 );
create table movie (runtime integer not null, genre varchar(255) not null, title varchar(255) not null, primary key (title)) engine=InnoDB;
create table room (col_count integer not null, row_count integer not null, room_name varchar(255) not null, primary key (room_name)) engine=InnoDB;
create table screening (screening_id integer not null auto_increment, start_time datetime(6) not null, movie_title_id varchar(255) not null, room_room_name_id varchar(255) not null, primary key (screening_id)) engine=InnoDB;
alter table _user add constraint UK_k11y3pdtsrjgy8w9b6q4bjwrx unique (email);
alter table screening add constraint FKg0h7o7un2cypdgqwpfmqohjiu foreign key (movie_title_id) references movie (title);
alter table screening add constraint FKtrw3ri1tre3m76deqsp2d6xqx foreign key (room_room_name_id) references room (room_name);
create table _user (id integer not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role enum ('USER','ADMIN'), primary key (id)) engine=InnoDB;
create table account (birth datetime(6), id bigint not null, address varchar(255), email varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table account_seq (next_val bigint) engine=InnoDB;
insert into account_seq values ( 1 );
create table movie (runtime integer not null, genre varchar(255) not null, title varchar(255) not null, primary key (title)) engine=InnoDB;
create table room (col_count integer not null, row_count integer not null, room_name varchar(255) not null, primary key (room_name)) engine=InnoDB;
create table screening (screening_id integer not null auto_increment, start_time datetime(6) not null, movie_title_id varchar(255) not null, room_room_name_id varchar(255) not null, primary key (screening_id)) engine=InnoDB;
alter table _user add constraint UK_k11y3pdtsrjgy8w9b6q4bjwrx unique (email);
alter table screening add constraint FKg0h7o7un2cypdgqwpfmqohjiu foreign key (movie_title_id) references movie (title);
alter table screening add constraint FKtrw3ri1tre3m76deqsp2d6xqx foreign key (room_room_name_id) references room (room_name);
create table _user (id integer not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role enum ('USER','ADMIN'), primary key (id)) engine=InnoDB;
create table account (birth datetime(6), id bigint not null, address varchar(255), email varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table account_seq (next_val bigint) engine=InnoDB;
insert into account_seq values ( 1 );
create table movie (runtime integer not null, genre varchar(255) not null, title varchar(255) not null, primary key (title)) engine=InnoDB;
create table room (col_count integer not null, row_count integer not null, room_name varchar(255) not null, primary key (room_name)) engine=InnoDB;
create table screening (screening_id integer not null auto_increment, start_time datetime(6) not null, movie_title_id varchar(255) not null, room_room_name_id varchar(255) not null, primary key (screening_id)) engine=InnoDB;
alter table _user add constraint UK_k11y3pdtsrjgy8w9b6q4bjwrx unique (email);
alter table screening add constraint FKg0h7o7un2cypdgqwpfmqohjiu foreign key (movie_title_id) references movie (title);
alter table screening add constraint FKtrw3ri1tre3m76deqsp2d6xqx foreign key (room_room_name_id) references room (room_name);
create table _user (id integer not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role enum ('USER','ADMIN'), primary key (id)) engine=InnoDB;
create table account (birth datetime(6), id bigint not null, address varchar(255), email varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table account_seq (next_val bigint) engine=InnoDB;
insert into account_seq values ( 1 );
create table movie (runtime integer not null, genre varchar(255) not null, title varchar(255) not null, primary key (title)) engine=InnoDB;
create table room (col_count integer not null, row_count integer not null, room_name varchar(255) not null, primary key (room_name)) engine=InnoDB;
create table screening (screening_id integer not null auto_increment, start_time datetime(6) not null, movie_title_id varchar(255) not null, room_room_name_id varchar(255) not null, primary key (screening_id)) engine=InnoDB;
alter table _user add constraint UK_k11y3pdtsrjgy8w9b6q4bjwrx unique (email);
alter table screening add constraint FKg0h7o7un2cypdgqwpfmqohjiu foreign key (movie_title_id) references movie (title);
alter table screening add constraint FKtrw3ri1tre3m76deqsp2d6xqx foreign key (room_room_name_id) references room (room_name);
